name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install trunk
      run: cargo install trunk
    - name: Save environment
      run: |
        echo APP_BACKEND_URL=${{ vars.APP_BACKEND_URL }} > .env
        echo APP_CART_URL=${{ vars.APP_CART_URL }} >> .env
        echo APP_DEFAULT_PRODUCT_IMAGE=${{ vars.APP_DEFAULT_PRODUCT_IMAGE }} >> .env
    - name: Build
      run: trunk build --release
    # - name: Run tests
    #   run: cargo test --verbose
