name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Save environment
      run: |
        echo ${{ vars.APP_BACKEND_URL }} > .env
        echo ${{ vars.APP_CART_URL }} >> .env
        echo ${{ vars.APP_DEFAULT_PRODUCT_IMAGE }} >> .env
        cat .env
    # - name: Build
    #   run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
